version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: primsadb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres:123123@db:5432/primsadb?schema=public"
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && npx prisma generate && node dist/index.js"

volumes:
  postgres_data:
